Repository gradsflow/chitra, pull requests merged in 2021-07, with the labels that each got.

#86 Migrate to black
  .pre-commit-config.yaml
  Makefile
  chitra/constants.py
  chitra/converter/core.py
  chitra/coordinates.py
  chitra/core.py
  chitra/datagenerator.py
  chitra/dataloader.py
  chitra/image.py
  chitra/logging.py
  chitra/serve/model_server.py
  chitra/serve/schema/__init__.py
  chitra/serve/tf_serving/client.py
  chitra/tf_image.py
  chitra/trainer.py
  chitra/utility/import_utils.py
  chitra/utility/tf_utils.py
  chitra/visualization/metrics.py
  pyproject.toml
  tests/test_coordinates.py
  tests/test_core.py
  tests/test_datagenerator.py
  tests/test_dataloader.py
  tests/test_image.py
  tests/test_import_utils.py
  tests/test_model_server.py
  tests/test_tf_image.py
  tests/test_tf_serving_client.py
  tests/test_tf_utils.py
  tests/test_trainer.py
  tests/test_visualization_metrics.py
Labels: design, enhancement

#87 resize bounding box with image.resize()
  chitra/coordinates.py
  chitra/dataloader.py
  chitra/image.py
  examples/examples/image/coordinates.py
  tests/test_coordinates.py
  tests/test_image.py
Labels: enhancement

#89 add dataprocess pipeline and class based model serving
  Makefile
  chitra/serve/data_processing/__init__.py
  chitra/serve/data_processing/processor.py
  chitra/serve/data_processing/vision.py
  chitra/serve/model_server.py
  examples/src/image/coordinates.py
  examples/src/image/play_with_images.py
  examples/src/model_server.py
  examples/src/visualization/confusion_matrix.py
  tests/test_model_server.py
Labels: design, enhancement

#93 refactor API & Docs
  README.md
  chitra/__about__.py
  chitra/__init__.py
  chitra/dataloader.py
  chitra/image.py
  chitra/logging.py
  chitra/serve/__init__.py
  chitra/serve/data_processing/processor.py
  chitra/serve/data_processing/vision.py
  chitra/serve/model_server.py
  chitra/serve/schema/__init__.py
  chitra/utility/import_utils.py
  docs/index.md
  docs/source/api/image/chitra-class.md
  docs/source/api/image/output_6_0.png
  docs/source/api/image/output_8_1.png
  docs/source/api/serve/model_server.md
  docs/source/api/serve/preview-qna.png
  docs/source/api/visualization/metrics.md
  docs/source/api/visualization/preview.png
  examples/src/serve/text_classification_api.py
  mkdocs.yml
  pyproject.toml
Labels: design, documentation, enhancement

#95 Integrate Gradio
  .pre-commit-config.yaml
  README.md
  chitra/__about__.py
  chitra/__init__.py
  chitra/coordinates.py
  chitra/core.py
  chitra/datagenerator.py
  chitra/dataloader.py
  chitra/image.py
  chitra/serve/__init__.py
  chitra/serve/api.py
  chitra/serve/app.py
  chitra/serve/constants.py
  chitra/serve/data_processing/vision.py
  chitra/serve/model_server.py
  chitra/tf_image.py
  chitra/trainer.py
  chitra/utility/tf_utils.py
  chitra/visualization/metrics.py
  docs/index.md
  examples/src/serve/gradio_app.py
  pyproject.toml
  tests/serve/__init__.py
  tests/serve/test_api.py
  tests/serve/test_app.py
  tests/serve/test_tf_serving_client.py
  tests/test_model_server.py
Labels: documentation, enhancement

#97 refactor model server
  .deepsource.toml
  chitra/__init__.py
  chitra/data_processing/__init__.py
  chitra/data_processing/default/__init__.py
  chitra/data_processing/default/nlp.py
  chitra/data_processing/default/vision.py
  chitra/data_processing/processor.py
  chitra/dataloader.py
  chitra/serve/api.py
  chitra/serve/app.py
  chitra/serve/data_processing/__init__.py
  chitra/serve/data_processing/processor.py
  chitra/serve/model_server.py
  chitra/serve/tf_serving/client.py
  tests/data_processing/default/test_vision.py
  tests/data_processing/test_processor.py
  tests/serve/test_api.py
  tests/serve/test_app.py
  tests/serve/test_model_server.py
  tests/serve/test_tf_serving_client.py
  tests/test_tf_utils.py
Labels: bug, design, test

#98 fixes 0.1.0rc0
  README.md
  chitra/__init__.py
  chitra/serve/app.py
  chitra/serve/torchserve/__init__.py
  docs/index.md
  docs/source/api/serve/model_server.md
  examples/src/serve/gradio_app.py
  pyproject.toml
  tests/serve/test_app.py
Labels: documentation

#100 fix doc inconsistency
  .github/labeler.yml
  .github/workflows/labeler.yml
  .github/workflows/main.yml
  README.md
  docs/index.md
  docs/source/api/serve/model_server.md
  docs/source/api/serve/preview-app-image-clf.png
  mkdocs.yml
  pyproject.toml
Labels: documentation

#102 chitra new banner
  docs/assets/chitra_banner_0.1.0.png
  docs/overrides/main.html
  mkdocs.yml
Labels: documentation

#101 🚀 increase coverage
  chitra/converter/core.py
  chitra/datagenerator.py
  chitra/trainer.py
  tests/serve/test_api.py
Labels: test

#104 Release Prep
  README.md
  chitra/__init__.py
  chitra/utility/__init__.py
  docs/assets/chitra_banner_0.1.0.png
  docs/assets/favicon/android-chrome-192x192.png
  docs/assets/favicon/android-chrome-512x512.png
  docs/assets/favicon/apple-touch-icon.png
  docs/assets/favicon/favicon-16x16.png
  docs/assets/favicon/favicon-32x32.png
  docs/assets/favicon/favicon.ico
  docs/examples/chitra-class/chitra-class.md
  docs/examples/image-classification/image-classification.md
  docs/examples/model-server/model-server.md
  docs/index.md
  docs/source/api/image/chitra-class.md
  docs/source/api/serve/model_server.md
  mkdocs.yml
Labels: documentation

#110 remove heavy imports
  .pre-commit-config.yaml
  chitra/__init__.py
  chitra/cli/__init__.py
  chitra/cli/main.py
  chitra/image.py
  chitra/imports.py
  chitra/logging.py
  chitra/utility/import_utils.py
  pyproject.toml
  tests/serve/test_api.py
  tests/test_tf_image.py
Labels: enhancement, test

#111 Add CLI support
  chitra/cli/__init__.py
  chitra/cli/dockerize.py
  chitra/cli/main.py
  chitra/converter/core.py
  docker-images/Dockerfile
  docker-images/serverless/lambda.Dockerfile
  examples/nbs/playground.ipynb
  examples/src/docker/docker_api.py
  pyproject.toml
  requirements/converter.txt
  requirements/dev.txt
  requirements/docs.txt
  requirements/serve.txt
  requirements/test.txt
  requirements/tf.txt
  requirements/torch.txt
  sonar-project.properties
  tests/cli/test_dockerize.py
  tests/cli/test_main.py
Labels: enhancement, test

#112 fix requirements.txt for mkdocs
  .readthedocs.yaml
  docs/requirements.txt
Labels: bug, documentation
